// Auto-generated by build.js — do not edit manually
// Last built: 2026-04-29T23:02:21.350Z
// Source: guides/*.md

const SHEET_DEFS_META = [
  {
    "id": 1,
    "name": "Everything Claude Code",
    "file": "Everything-Claude-Code",
    "cat": "agent",
    "catLabel": "AI Agent",
    "color": "#fc5c7c",
    "desc": "Master agent toolkit — 36 agents, 80+ skills, 30+ commands",
    "links": [
      2,
      3,
      4,
      5,
      6,
      14
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 2,
    "name": "Claude Code Plugins",
    "file": "Claude-Code-Plugins",
    "cat": "agent",
    "catLabel": "AI Agent",
    "color": "#fc5c7c",
    "desc": "Plugin management — install, update, MCP servers",
    "links": [
      1,
      3,
      5,
      14,
      6
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 3,
    "name": "Claude Code Skills",
    "file": "Claude-Code-Skills",
    "cat": "agent",
    "catLabel": "AI Agent",
    "color": "#fc5c7c",
    "desc": "Skill definitions — 1 custom, 6 GitNexus, 14 cluster",
    "links": [
      1,
      2,
      7,
      4
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 4,
    "name": "Claude Code Agents",
    "file": "Claude-Code-Agents",
    "cat": "agent",
    "catLabel": "AI Agent",
    "color": "#fc5c7c",
    "desc": "7 AI roles with permissions and boundaries",
    "links": [
      1,
      3,
      7,
      6,
      15
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 5,
    "name": "Claude-Mem",
    "file": "Claude-Mem",
    "cat": "agent",
    "catLabel": "AI Agent",
    "color": "#fc5c7c",
    "desc": "Persistent memory — SQLite + ChromaDB",
    "links": [
      1,
      2,
      4
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 6,
    "name": "Codex CLI",
    "file": "Codex-CLI",
    "cat": "agent",
    "catLabel": "AI Agent",
    "color": "#fc5c7c",
    "desc": "Adversarial reviewer / FIA — SELECT only",
    "links": [
      1,
      4,
      14,
      2
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 7,
    "name": "GitNexus",
    "file": "GitNexus",
    "cat": "intel",
    "catLabel": "Code Intel",
    "color": "#fcac5c",
    "desc": "Knowledge graph — 1,424 symbols, impact analysis",
    "links": [
      3,
      4,
      8,
      1
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 8,
    "name": "Graphify",
    "file": "Graphify",
    "cat": "intel",
    "catLabel": "Code Intel",
    "color": "#fcac5c",
    "desc": "Visual graph generator — code to HTML+JSON",
    "links": [
      7,
      3
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 9,
    "name": "Playwright MCP",
    "file": "Playwright-MCP",
    "cat": "test",
    "catLabel": "Testing",
    "color": "#7c5cfc",
    "desc": "Browser automation — navigate, click, screenshot",
    "links": [
      14,
      1,
      15
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 10,
    "name": "Obsidian MCP",
    "file": "Obsidian-MCP",
    "cat": "mcp",
    "catLabel": "MCP",
    "color": "#5cfc9c",
    "desc": "Vault MCP bridge — port 3010 to REST API 27124",
    "links": [
      13,
      14,
      11,
      12
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 11,
    "name": "Obsidian API Reader",
    "file": "Obsidian-API-Reader",
    "cat": "mcp",
    "catLabel": "MCP",
    "color": "#5cfc9c",
    "desc": "Direct PowerShell/batch REST vault access",
    "links": [
      10,
      13,
      12
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 12,
    "name": "Sync-To-Obsidian",
    "file": "Sync-To-Obsidian",
    "cat": "mcp",
    "catLabel": "MCP",
    "color": "#5cfc9c",
    "desc": "Project-to-vault sync with routing rules",
    "links": [
      10,
      11,
      13
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 13,
    "name": "MCP Scripts",
    "file": "MCP-Scripts",
    "cat": "mcp",
    "catLabel": "MCP",
    "color": "#5cfc9c",
    "desc": "7 launcher scripts — HTTP, stdio, clean restart",
    "links": [
      14,
      10,
      11,
      12
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 14,
    "name": "MCP Tool Configs",
    "file": "MCP-Tool-Configs",
    "cat": "mcp",
    "catLabel": "MCP",
    "color": "#5cfc9c",
    "desc": "Per-tool JSON configs — Windsurf, Claude, ChatGPT, Codex",
    "links": [
      13,
      10,
      2,
      1,
      6
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 15,
    "name": "Windsurf Rules",
    "file": "Windsurf-Rules",
    "cat": "rules",
    "catLabel": "Rules",
    "color": "#5cfcdc",
    "desc": "Terminal raw mode, frontend-only boundaries",
    "links": [
      4,
      9,
      1
    ],
    "updated": "Apr 29, 2026"
  },
  {
    "id": 16,
    "name": "500 AI Projects Reference",
    "file": "500-AI-Projects-Reference",
    "cat": "ref",
    "catLabel": "Reference",
    "color": "#fcdc5c",
    "desc": "500+ ML/DL projects mapped to Tri-Lens",
    "links": [],
    "updated": "Apr 29, 2026"
  }
];

const MD_CONTENT = {

"Everything-Claude-Code": `---

## What It Is

A complete performance optimization system for AI coding agents. Not just configs — it includes skills, agents, hooks, rules, memory, security scanning, continuous learning, and research-first development workflows.

Works across: **Claude Code, Codex, Cursor, OpenCode, Gemini**

---

## Install / Update

\`\`\`bash
# Plugin install (recommended)
/plugin marketplace add https://github.com/affaan-m/everything-claude-code
/plugin install everything-claude-code@everything-claude-code

# OR manual install via npm
npx ecc-install --profile full

# OR manual install via shell
curl -fsSL https://raw.githubusercontent.com/affaan-m/everything-claude-code/main/install.sh | bash -s -- --profile full
\`\`\`

**Do NOT stack install methods.** Pick one path only.

### Naming Reference
| Identifier | Use |
|-----------|-----|
| \`affaan-m/everything-claude-code\` | GitHub repo |
| \`everything-claude-code@everything-claude-code\` | Plugin install ID |
| \`ecc-universal\` | npm package |

### Reset / Uninstall
\`\`\`bash
/plugin uninstall everything-claude-code
\`\`\`

---

## 36 Agents (Subagents for Delegation)

### Core Workflow
| Agent | What It Does |
|-------|-------------|
| \`planner.md\` | Feature implementation planning |
| \`architect.md\` | System design decisions |
| \`tdd-guide.md\` | Test-driven development |
| \`code-reviewer.md\` | Quality and security review |
| \`security-reviewer.md\` | Vulnerability analysis |
| \`build-error-resolver.md\` | Fix build errors |
| \`e2e-runner.md\` | Playwright E2E testing |
| \`refactor-cleaner.md\` | Dead code cleanup |
| \`doc-updater.md\` | Documentation sync |
| \`docs-lookup.md\` | Documentation/API lookup |
| \`chief-of-staff.md\` | Communication triage and drafts |
| \`loop-operator.md\` | Autonomous loop execution |
| \`harness-optimizer.md\` | Harness config tuning |

### Language-Specific Reviewers
| Agent | Language |
|-------|---------|
| \`python-reviewer.md\` | Python |
| \`typescript-reviewer.md\` | TypeScript/JavaScript |
| \`go-reviewer.md\` | Go |
| \`java-reviewer.md\` | Java/Spring Boot |
| \`kotlin-reviewer.md\` | Kotlin/Android |
| \`rust-reviewer.md\` | Rust |
| \`cpp-reviewer.md\` | C++ |
| \`database-reviewer.md\` | Database/Supabase |

### Build Error Resolvers
| Agent | Language |
|-------|---------|
| \`go-build-resolver.md\` | Go |
| \`java-build-resolver.md\` | Java/Maven/Gradle |
| \`kotlin-build-resolver.md\` | Kotlin/Gradle |
| \`rust-build-resolver.md\` | Rust |
| \`cpp-build-resolver.md\` | C++ |
| \`pytorch-build-resolver.md\` | PyTorch/CUDA |

---

## 80+ Skills (Workflow Definitions)

### Development Patterns
| Skill | What It Covers |
|-------|---------------|
| \`coding-standards/\` | Language best practices |
| \`backend-patterns/\` | API, database, caching patterns |
| \`frontend-patterns/\` | React, Next.js patterns |
| \`python-patterns/\` | Python idioms and best practices |
| \`golang-patterns/\` | Go idioms and best practices |
| \`postgres-patterns/\` | PostgreSQL optimization |
| \`api-design/\` | REST API design, pagination, errors |
| \`docker-patterns/\` | Docker Compose, networking, security |
| \`deployment-patterns/\` | CI/CD, health checks, rollbacks |
| \`database-migrations/\` | Prisma, Drizzle, Django, Go migrations |

### Testing & Security
| Skill | What It Covers |
|-------|---------------|
| \`tdd-workflow/\` | Test-driven development methodology |
| \`security-review/\` | Security checklist |
| \`security-scan/\` | AgentShield security auditor |
| \`e2e-testing/\` | Playwright patterns and Page Object Model |
| \`python-testing/\` | pytest patterns |
| \`golang-testing/\` | Go TDD, benchmarks |
| \`verification-loop/\` | Continuous verification |
| \`eval-harness/\` | Verification loop evaluation |

### AI & Optimization
| Skill | What It Covers |
|-------|---------------|
| \`continuous-learning-v2/\` | Instinct-based learning with confidence scoring |
| \`iterative-retrieval/\` | Progressive context refinement for subagents |
| \`strategic-compact/\` | Manual compaction suggestions |
| \`search-first/\` | Research-before-coding workflow |
| \`cost-aware-llm-pipeline/\` | LLM cost optimization, model routing |
| \`autonomous-loops/\` | Sequential pipelines, PR loops, DAG orchestration |

### Content & Business
| Skill | What It Covers |
|-------|---------------|
| \`article-writing/\` | Long-form writing without AI tone |
| \`content-engine/\` | Multi-platform social content |
| \`market-research/\` | Source-attributed research |
| \`investor-materials/\` | Pitch decks, memos, financial models |
| \`investor-outreach/\` | Personalized fundraising outreach |
| \`frontend-slides/\` | HTML slide decks and PPTX-to-web |

### Framework-Specific
| Skill | Framework |
|-------|-----------|
| \`django-patterns/\` | Django models, views |
| \`django-security/\` | Django security |
| \`django-tdd/\` | Django TDD workflow |
| \`laravel-patterns/\` | Laravel architecture |
| \`laravel-security/\` | Laravel security |
| \`springboot-patterns/\` | Java Spring Boot |
| \`springboot-security/\` | Spring Boot security |
| \`clickhouse-io/\` | ClickHouse analytics |

---

## 30+ Slash Commands

### Core Commands
| Command | What It Does |
|---------|-------------|
| \`/plan\` | Implementation planning |
| \`/tdd\` | Test-driven development |
| \`/e2e\` | E2E test generation |
| \`/code-review\` | Quality review |
| \`/build-fix\` | Fix build errors |
| \`/refactor-clean\` | Dead code removal |
| \`/verify\` | Run verification loop |
| \`/checkpoint\` | Save verification state |
| \`/eval\` | Evaluate against criteria |
| \`/test-coverage\` | Test coverage analysis |
| \`/update-docs\` | Update documentation |
| \`/update-codemaps\` | Update codemaps |

### Learning & Instincts
| Command | What It Does |
|---------|-------------|
| \`/learn\` | Extract patterns mid-session |
| \`/learn-eval\` | Extract, evaluate, and save patterns |
| \`/instinct-status\` | View learned instincts |
| \`/instinct-import\` | Import instincts |
| \`/instinct-export\` | Export instincts |
| \`/evolve\` | Cluster instincts into skills |
| \`/prune\` | Delete expired pending instincts |
| \`/skill-create\` | Generate skills from git history |

### Multi-Agent Orchestration
| Command | What It Does |
|---------|-------------|
| \`/multi-plan\` | Multi-agent task decomposition |
| \`/multi-execute\` | Orchestrated multi-agent workflows |
| \`/multi-backend\` | Backend multi-service orchestration |
| \`/multi-frontend\` | Frontend multi-service orchestration |
| \`/multi-workflow\` | General multi-service workflows |
| \`/orchestrate\` | Multi-agent coordination |

### Language-Specific
| Command | What It Does |
|---------|-------------|
| \`/go-review\` | Go code review |
| \`/go-test\` | Go TDD workflow |
| \`/go-build\` | Fix Go build errors |
| \`/python-review\` | Python code review |
| \`/pm2\` | PM2 service lifecycle management |
| \`/sessions\` | Session history management |
| \`/setup-pm\` | Configure package manager |

---

## Hooks (Auto-Triggers)

| Hook | When It Fires | What It Does |
|------|--------------|-------------|
| \`session-start.js\` | Session begins | Loads context and state |
| \`session-end.js\` | Session ends | Saves state and patterns |
| \`pre-compact.js\` | Before compaction | Saves pre-compaction state |
| \`suggest-compact.js\` | Context window filling | Suggests strategic compaction |
| \`evaluate-session.js\` | Session evaluation | Extracts patterns from sessions |

---

## Rules (Always-On Guidelines)

| Rule File | What It Enforces |
|-----------|-----------------|
| \`coding-style.md\` | Immutability, file organization |
| \`git-workflow.md\` | Commit format, PR process |
| \`testing.md\` | TDD, 80% coverage requirement |
| \`performance.md\` | Model selection, context management |
| \`patterns.md\` | Design patterns, skeleton projects |
| \`hooks.md\` | Hook architecture, TodoWrite |
| \`agents.md\` | When to delegate to subagents |
| \`security.md\` | Mandatory security checks |

Language-specific rule sets: TypeScript, Python, Go, Swift, PHP

---

## Context Modes

| Mode | File | When to Use |
|------|------|-------------|
| Development | \`dev.md\` | Building features, writing code |
| Review | \`review.md\` | Code review, quality checks |
| Research | \`research.md\` | Exploring, investigating, learning |

---

## Most Relevant for Tri-Lens

| ECC Feature | Tri-Lens Use Case |
|-------------|-------------------|
| \`security-scan/\` | AgentShield — automated secret detection (like our gitleaks scan) |
| \`database-reviewer.md\` | Review scoring engine DB queries |
| \`python-reviewer.md\` | Review Python pipeline scripts |
| \`postgres-patterns/\` | Optimize PostgreSQL queries for signals_raw, score_history |
| \`deployment-patterns/\` | CI/CD for GCP Cloud Functions |
| \`continuous-learning-v2/\` | Learn Tri-Lens patterns over time |
| \`tdd-workflow/\` | Add test coverage to scoring engine |
| \`verification-loop/\` | Continuous verification of pipeline changes |
| \`/plan\` | Planning new features like the dashboard |
| \`/code-review\` | Review before merging to staging/main |

---

## Dashboard GUI

ECC includes a desktop dashboard:
\`\`\`bash
python ecc_dashboard.py
\`\`\`
Opens a Tkinter GUI to manage skills, agents, hooks, and commands visually.

---

## Example CLAUDE.md Configs

ECC provides real-world example configs:
| Example | Stack |
|---------|-------|
| \`saas-nextjs-CLAUDE.md\` | Next.js + Supabase + Stripe |
| \`go-microservice-CLAUDE.md\` | Go gRPC + PostgreSQL |
| \`django-api-CLAUDE.md\` | Django REST API + Celery |
| \`laravel-api-CLAUDE.md\` | Laravel + PostgreSQL + Redis |
| \`rust-api-CLAUDE.md\` | Rust Axum + SQLx + PostgreSQL |

---

## MCP Configs Included

Pre-built MCP server configs for: GitHub, Supabase, Vercel, Railway, and more.
File: \`mcp-configs/mcp-servers.json\`

---

## Links

- **Repo:** https://github.com/affaan-m/everything-claude-code
- **Releases:** https://github.com/affaan-m/everything-claude-code/releases
- **Marketplace:** \`everything-claude-code@everything-claude-code\`
- **npm:** \`ecc-universal\`

---`,

"Claude-Code-Plugins": `---

## Installed Plugins

| Plugin | Version | What It Does |
|--------|---------|-------------|
| **everything-claude-code** | v2.0.0-rc.1 | Full agent harness — skills, agents, hooks, rules, memory |
| **claude-mem** | Latest | Persistent memory across sessions (SQLite + ChromaDB) |
| **superpowers** | Latest | Extended capabilities for Claude Code |

## Plugin Commands

\`\`\`bash
# List installed plugins
/plugin list

# Install a plugin
/plugin install <name>

# Uninstall a plugin
/plugin uninstall <name>

# Add marketplace source
/plugin marketplace add <url>
\`\`\`

## MCP Servers Configured

| Server | Transport | Config Location |
|--------|-----------|----------------|
| Obsidian | HTTP (serverUrl) | \`mcp-configs/windsurf-mcp_config.json\` |
| Obsidian (Claude Desktop) | stdio | \`mcp-configs/claude-desktop-config.json\` |
| Obsidian (ChatGPT) | stdio | \`mcp-configs/chatgpt-mcp-config.json\` |
| Obsidian (Codex) | stdio | \`mcp-configs/codex-mcp-config.json\` |
| Obsidian (Gemini) | stdio | \`mcp-configs/gemini-mcp-config.json\` |

## Settings File

Claude Code settings: \`~/.claude/settings.json\`

To enable/disable plugins, edit the \`plugins\` array in settings.`,

"Claude-Code-Skills": `---

## What Are Skills?

Skills are workflow definitions that teach Claude Code how to perform specific tasks. They live in \`.claude/skills/\` as markdown files with YAML frontmatter.

## Installed Skills (3 Categories)

### Custom Skills (1)

| Skill | Location | What It Does |
|-------|----------|-------------|
| **scoring-engine-owner** | \`.claude/skills/custom/scoring-engine-owner/\` | Own and operate a production scoring engine — calibration, monitoring, governance, incident response |

**Sub-files:**
- \`SKILL.md\` — Main workflow (6-step scoring lifecycle)
- \`agents/openai.yaml\` — OpenAI agent config
- \`assets/score-incident-runbook-template.md\` — Incident response template
- \`assets/scoring-contract-template.md\` — Scoring contract template
- \`references/modern-experts.md\` — Modern scoring methods
- \`references/persona-playbook.md\` — Implementation patterns

### GitNexus Skills (6)

| Skill | What It Does | Trigger |
|-------|-------------|---------|
| **gitnexus-guide** | Tools, resources, schema reference | "What GitNexus tools are available?" |
| **gitnexus-exploring** | Navigate architecture, understand code | "How does X work?" |
| **gitnexus-impact-analysis** | Blast radius before editing | "What breaks if I change X?" |
| **gitnexus-debugging** | Trace bugs through execution flows | "Why is X failing?" |
| **gitnexus-refactoring** | Safe rename, extract, split | Refactoring tasks |
| **gitnexus-cli** | Index, status, clean, wiki commands | CLI management |

### Generated Skills (14 cluster-based)

Auto-generated by GitNexus based on codebase analysis:

| Skill | Symbols | Area |
|-------|---------|------|
| **archive** | 47 | Archive area code |
| **functions** | 43 | Firebase Cloud Functions |
| **etl** | 12 | ETL pipeline |
| **tests** | 11 | Test suite |
| **cluster-16** | 13 | Code cluster |
| **cluster-17** | 14 | Code cluster |
| **cluster-18** | 5 | Code cluster |
| **cluster-19** | 5 | Code cluster |
| **cluster-20** | 5 | Code cluster |
| **cluster-29** | 3 | Code cluster |
| **cluster-30** | 3 | Code cluster |
| **cluster-50** | 3 | Code cluster |
| **cluster-51** | 7 | Code cluster |
| **cluster-85** | 3 | Code cluster |
| **cluster-86** | 3 | Code cluster |

## Skill File Format

\`\`\`markdown
---
name: my-skill
description: "When to trigger this skill"
---

# Skill Name

Steps and instructions here...
\`\`\`

## How to Use Skills

Skills are automatically invoked when Claude Code detects a matching trigger in your prompt. You can also reference them directly:
- "Use the scoring-engine-owner skill to review this proposal"
- "Follow the gitnexus-debugging workflow to trace this bug"

## How to Create New Skills

1. Create folder: \`.claude/skills/custom/<skill-name>/\`
2. Add \`SKILL.md\` with frontmatter + workflow steps
3. Optionally add \`assets/\`, \`references/\`, \`agents/\` subfolders

---`,

"Claude-Code-Agents": `---

## What Are Agents?

Agents are specialized AI roles that operate within the Tri-Lens system. Each has defined responsibilities, permissions, and boundaries.

## Active Agents (7 Roles)

### Strategy & Architecture

| Agent | Role | Owns | Does NOT |
|-------|------|------|----------|
| **Claude (chat)** | Lead Architect | Decisions, missions, roadmap, patent, ClickUp PM | Execute code, deploy, touch files |
| **Gemini** | Architecture Validator | Confirm SQL, scoring logic | Make changes |
| **ChatGPT** | Secondary Confirmer | Patent language, API docs | Make changes |

### Execution

| Agent | Role | Owns | Does NOT |
|-------|------|------|----------|
| **Claude Code** | Backend Dev | Tests, deploys, DB queries, file edits | Make decisions, deploy without test gate |
| **Lovable** | Frontend Dev | UI, React, Firebase apps.siiya.online | Backend, DB, pipeline |
| **Windsurf** | Frontend Execution | React/UI components, frontend deploys | Backend pipeline, DB operations |

### Verification & Security

| Agent | Role | Owns | Does NOT |
|-------|------|------|----------|
| **Codex** | Adversarial Reviewer / FIA | Find violations, red-team, forensic audits | Make changes, suggest architecture |
| **Signal Integrity Statistician** | Independent statistical authority | Distribution analysis, dormant defect detection, ship-blocker calls | Propose architecture, write production code |
| **Verification Agent (Test)** | Verification authority | Read-only verification of every claim, audit reports | Write production code, propose architecture |

## Codex FIA Constraints (CRITICAL)

- CAN execute SELECT queries for verification only
- CANNOT git commit or gcloud deploy
- CANNOT access production secrets
- MANDATE: identify B1-B7 blocking issues only

## Statistician Role

- Read-only DB access via \`trilens_statistician_ro\` role
- Full CRUD on \`statistician_analysis\` schema only
- System prompt: \`governance/role_definitions/signal_integrity_statistician_system_prompt.md\`
- Reports directly to Owner — does not route through Lead Architect
- Universal Callout Authority — flags structural issues regardless of scope

## Verification Agent (Test v5)

- Read-only access to GitHub, ClickUp, and DB
- System prompt: \`governance/role_definitions/verification_agent_test_system_prompt.md\`
- Operates in two layers (Hybrid Verification Mandate):
  - **Layer 1:** In-session self-check after every task
  - **Layer 2:** Session-end independent audit gate
- Reports directly to Owner

## GitNexus Code Intelligence

GitNexus indexes the repo as \`tri-lens-pipeline\` (1424 symbols, 1850 relationships, 44 execution flows).

| Tool | Purpose |
|------|---------|
| \`gitnexus_query\` | Find code by concept |
| \`gitnexus_context\` | 360-degree symbol view |
| \`gitnexus_impact\` | Blast radius before editing |
| \`gitnexus_detect_changes\` | Pre-commit scope check |
| \`gitnexus_rename\` | Safe multi-file rename |
| \`gitnexus_cypher\` | Custom graph queries |

## Key Rules for All Agents

1. MUST run impact analysis before editing any symbol
2. MUST run \`gitnexus_detect_changes()\` before committing
3. MUST warn user if impact analysis returns HIGH or CRITICAL risk
4. NEVER edit without running \`gitnexus_impact\` first
5. NEVER rename with find-and-replace — use \`gitnexus_rename\`

---`,

"Claude-Mem": `---

## What It Does

Claude-Mem gives Claude Code long-term memory that persists between sessions. It stores facts, decisions, and context in a local database so Claude Code can recall previous conversations and decisions.

## How It Works

1. **Lifecycle Hooks** — Automatically saves context at session start/end
2. **Storage** — SQLite for structured data, ChromaDB for vector search
3. **Retrieval** — MCP search tools for querying stored memories

## Install / Update

\`\`\`bash
# Install as Claude Code plugin
claude plugin install claude-mem

# Or via npm
npm install -g claude-mem
\`\`\`

## Storage Locations

| Store | Location | Purpose |
|-------|----------|---------|
| SQLite DB | \`~/.claude-mem/memory.db\` | Structured facts, decisions |
| ChromaDB | \`~/.claude-mem/chroma/\` | Vector embeddings for semantic search |

## MCP Search Tools

| Tool | What It Does |
|------|-------------|
| \`memory_search\` | Semantic search across stored memories |
| \`memory_add\` | Add a new memory entry |
| \`memory_list\` | List recent memories |
| \`memory_delete\` | Remove a memory entry |

## Web Viewer

Claude-Mem includes a web UI to browse stored memories:
\`\`\`bash
claude-mem viewer
\`\`\`
Opens a local web interface to search, browse, and manage memories.

## Configuration

Config file: \`~/.claude-mem/config.json\`

\`\`\`json
{
  "storage": "sqlite",
  "embedding_model": "default",
  "auto_save": true,
  "max_memories": 10000
}
\`\`\`

## System Requirements

- Node.js 18+
- Claude Code CLI installed
- ~100MB disk space for databases

## Troubleshooting

| Issue | Fix |
|-------|-----|
| Memory not saving | Check \`auto_save: true\` in config |
| Search returns nothing | Run \`claude-mem reindex\` to rebuild vectors |
| DB corrupted | Delete \`~/.claude-mem/\` and restart |
| Plugin not loading | Run \`claude plugin list\` to verify installation |

## Tri-Lens Usage

Claude-Mem stores:
- Architecture decisions (ADRs)
- Scoring formula changes
- Database schema state
- Session context for handoffs between agents

---`,

"Codex-CLI": `---

## What It Is

OpenAI Codex CLI is an AI coding agent that reads your codebase, creates branches, writes code, and submits changes. In Tri-Lens, it's used as the adversarial reviewer (FIA) — it red-teams and audits code for violations.

## Install

\`\`\`bash
npm install -g @openai/codex
\`\`\`

## Usage

\`\`\`bash
# Start Codex in a repo
codex

# Start with a specific task
codex "review the scoring engine for vulnerabilities"

# Use with MCP config
codex --mcp-config mcp-configs/codex-mcp-config.json
\`\`\`

## Codex FIA Constraints in Tri-Lens (CRITICAL)

| Can Do | Cannot Do |
|--------|-----------|
| ✅ Execute SELECT queries for verification | ❌ git commit |
| ✅ Read files and code | ❌ gcloud deploy |
| ✅ Create branches for review | ❌ Access production secrets |
| ✅ Identify B1-B7 blocking issues | ❌ Make architecture changes |
| ✅ Write audit reports | ❌ Suggest architecture alternatives |

## Branches Codex Creates

Codex creates branches with the \`codex/\` prefix:
\`\`\`
codex/recommend-skills-for-scoring-engine-agent
codex/review-alignment-of-scoring-architecture-changes
codex/run-adversary-handoff-on-last-changes
\`\`\`

These should be reviewed, merged to dev, then deleted.

## MCP Config

File: \`mcp-configs/codex-mcp-config.json\`

Install location: \`~/.codex/mcp.json\`

## Tri-Lens Usage

| Task | How |
|------|-----|
| Red-team scoring logic | \`codex "adversarial review of scoring formula"\` |
| Audit governance compliance | \`codex "check all files against CLAUDE.md rules"\` |
| Find security issues | \`codex "scan for hardcoded credentials"\` |
| Verify test coverage | \`codex "identify untested code paths"\` |`,

"GitNexus": `---

## What It Is

GitNexus is a code intelligence engine that builds a knowledge graph of your codebase. It maps every function, class, import, and execution flow so AI agents can understand code structure, assess change impact, and navigate safely.

## Install / Update Index

\`\`\`bash
# Analyze codebase and build index
npx gitnexus analyze

# Analyze with embeddings (for semantic search)
npx gitnexus analyze --embeddings

# Check index freshness
# Read gitnexus://repo/tri-lens-pipeline/context
\`\`\`

## MCP Tools

| Tool | Command | When to Use |
|------|---------|-------------|
| **query** | \`gitnexus_query({query: "auth validation"})\` | Find code by concept |
| **context** | \`gitnexus_context({name: "validateUser"})\` | 360-degree symbol view |
| **impact** | \`gitnexus_impact({target: "X", direction: "upstream"})\` | Blast radius before editing |
| **detect_changes** | \`gitnexus_detect_changes({scope: "staged"})\` | Pre-commit scope check |
| **rename** | \`gitnexus_rename({symbol_name: "old", new_name: "new", dry_run: true})\` | Safe multi-file rename |
| **cypher** | \`gitnexus_cypher({query: "MATCH ..."})\` | Custom graph queries |
| **list_repos** | \`gitnexus_list_repos()\` | Discover indexed repos |

## MCP Resources (Read-Only)

| Resource | Content |
|----------|---------|
| \`gitnexus://repo/tri-lens-pipeline/context\` | Stats, staleness check |
| \`gitnexus://repo/tri-lens-pipeline/clusters\` | All functional areas |
| \`gitnexus://repo/tri-lens-pipeline/processes\` | All execution flows |
| \`gitnexus://repo/tri-lens-pipeline/process/{name}\` | Step-by-step trace |
| \`gitnexus://repo/tri-lens-pipeline/schema\` | Graph schema |

## Impact Risk Levels

| Depth | Meaning | Action |
|-------|---------|--------|
| d=1 | WILL BREAK — direct callers | MUST update |
| d=2 | LIKELY AFFECTED — indirect deps | Should test |
| d=3 | MAY NEED TESTING — transitive | Test if critical path |

## Skills Reference

| Task | Skill File |
|------|-----------|
| Understand architecture | \`.claude/skills/gitnexus/gitnexus-exploring/SKILL.md\` |
| Blast radius analysis | \`.claude/skills/gitnexus/gitnexus-impact-analysis/SKILL.md\` |
| Trace bugs | \`.claude/skills/gitnexus/gitnexus-debugging/SKILL.md\` |
| Refactoring | \`.claude/skills/gitnexus/gitnexus-refactoring/SKILL.md\` |
| Tools & schema | \`.claude/skills/gitnexus/gitnexus-guide/SKILL.md\` |
| CLI commands | \`.claude/skills/gitnexus/gitnexus-cli/SKILL.md\` |

## Mandatory Rules

1. **MUST** run \`gitnexus_impact\` before editing any function/class/method
2. **MUST** run \`gitnexus_detect_changes()\` before committing
3. **MUST** warn user if impact returns HIGH or CRITICAL risk
4. **NEVER** rename with find-and-replace — use \`gitnexus_rename\`
5. **NEVER** ignore HIGH/CRITICAL risk warnings

## Debugging Workflow

1. \`gitnexus_query({query: "<error or symptom>"})\` — find related flows
2. \`gitnexus_context({name: "<suspect function>"})\` — see callers/callees
3. Read \`gitnexus://repo/tri-lens-pipeline/process/{name}\` — trace full flow
4. For regressions: \`gitnexus_detect_changes({scope: "compare", base_ref: "main"})\`

## Keeping Index Fresh

\`\`\`bash
# After committing code changes
npx gitnexus analyze

# With embeddings preserved
npx gitnexus analyze --embeddings

# Check if embeddings exist
# Inspect .gitnexus/meta.json → stats.embeddings field
\`\`\`

A PostToolUse hook auto-refreshes after \`git commit\` and \`git merge\` in Claude Code.

---`,

"Graphify": `---

## What It Is

Graphify takes any input (code, docs, papers, images) and generates a knowledge graph with clustered communities. It produces HTML visualizations, JSON data, and audit reports.

## How to Use

Graphify is available as a Windsurf skill. Invoke it when you want to:
- Visualize code architecture as a knowledge graph
- Cluster related concepts from documentation
- Generate interactive HTML graph visualizations
- Create audit reports from complex data

## Output

| File | What It Contains |
|------|-----------------|
| \`graphify-out/graph.html\` | Interactive HTML visualization |
| \`graphify-out/graph.json\` | Raw graph data (nodes + edges) |
| \`graphify-out/audit.md\` | Audit report of clusters |
| \`graphify-out/cache/\` | Cached intermediate data |

## Trigger Phrases

- "Create a knowledge graph of..."
- "Visualize the architecture..."
- "Map the relationships between..."
- "Generate a graph from..."

## Tri-Lens Usage

Useful for:
- Visualizing scoring engine dependencies
- Mapping pipeline execution flows
- Creating architecture diagrams from code
- Documenting component relationships

---`,

"Playwright-MCP": `---

## What It Is

Playwright MCP gives AI agents full browser control via the Model Context Protocol. It enables web automation, testing, scraping, and interaction through AI tools like Claude Code and Windsurf.

## Four Components

| Component | What It Does | Command |
|-----------|-------------|---------|
| **Playwright Test** | E2E testing framework | \`npx playwright test\` |
| **Playwright CLI** | Browser management | \`npx playwright install\` |
| **Playwright MCP** | AI agent browser control via MCP | \`npx @anthropic-ai/mcp-playwright\` |
| **Playwright Library** | Programmatic browser API | \`import { chromium } from 'playwright'\` |

## Install

\`\`\`bash
# Install Playwright globally
npm install -g playwright

# Install Playwright MCP server
npm install -g @anthropic-ai/mcp-playwright

# Install browsers
npx playwright install
\`\`\`

## MCP Configuration

### For Claude Desktop
Add to \`claude_desktop_config.json\`:
\`\`\`json
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": ["@anthropic-ai/mcp-playwright"]
    }
  }
}
\`\`\`

### For Windsurf
Add to \`mcp_config.json\`:
\`\`\`json
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": ["@anthropic-ai/mcp-playwright"]
    }
  }
}
\`\`\`

## MCP Tools Available

| Tool | What It Does |
|------|-------------|
| \`browser_navigate\` | Go to a URL |
| \`browser_screenshot\` | Take a screenshot |
| \`browser_click\` | Click an element |
| \`browser_type\` | Type text into a field |
| \`browser_select\` | Select dropdown option |
| \`browser_evaluate\` | Execute JavaScript |
| \`browser_wait\` | Wait for element/condition |
| \`browser_close\` | Close the browser |

## Use Cases

| Task | Example |
|------|---------|
| Web scraping | Navigate to news site, extract article data |
| Form filling | Fill out and submit web forms |
| Testing | Verify UI elements and user flows |
| Screenshots | Capture page state for documentation |
| Monitoring | Check if a website is up and functioning |

## Playwright Test Example

\`\`\`javascript
import { test, expect } from '@playwright/test';

test('homepage loads', async ({ page }) => {
  await page.goto('https://apps.siiya.online');
  await expect(page).toHaveTitle(/SiiYa/);
});
\`\`\`

## Tri-Lens Usage

- Scrape GDELT news sources for pipeline validation
- Take dashboard screenshots for reports
- Test the Lovable UI at apps.siiya.online
- Monitor portal at trilens.siiya.online
- Automate browser-based data collection

## Troubleshooting

| Issue | Fix |
|-------|-----|
| Browsers not installed | \`npx playwright install\` |
| MCP not connecting | Restart AI tool after config change |
| Timeout errors | Increase timeout in test config |
| Headless issues | Add \`--headed\` flag for debugging |

---`,

"Obsidian-MCP": `---

## What It Is

The Obsidian MCP server bridges AI tools (Claude Code, Windsurf, ChatGPT, Codex, Gemini) to your local Obsidian vault via the Model Context Protocol. It reads, searches, and lists notes.

## Prerequisites

1. Obsidian running with the vault open
2. **Local REST API plugin** enabled (HTTPS on port 27124)
3. MCP server started via \`obsidian-mcp.bat\`

## Start the MCP Server

\`\`\`bash
cd c:\\Projects\\github\\tri-lens-pipeline
.\\obsidian-mcp.bat
\`\`\`
Keep this terminal open while using AI tools.

## MCP Tools Available

| Tool | What It Does |
|------|-------------|
| \`list_files\` | List all files in the vault |
| \`read_note\` | Read a specific note by path |
| \`search_notes\` | Search notes by keyword |
| \`list_folders\` | List vault folder structure |

## Config Files Per Tool

| AI Tool | Config File | Transport |
|---------|------------|-----------|
| Windsurf | \`mcp-configs/windsurf-mcp_config.json\` | HTTP (serverUrl) |
| Claude Desktop | \`mcp-configs/claude-desktop-config.json\` | stdio |
| ChatGPT | \`mcp-configs/chatgpt-mcp-config.json\` | stdio |
| Codex CLI | \`mcp-configs/codex-mcp-config.json\` | stdio |
| Gemini | \`mcp-configs/gemini-mcp-config.json\` | stdio |

## Testing Connection

After starting the MCP server and restarting your AI tool:
\`\`\`
List all files in my Obsidian vault
\`\`\`
or
\`\`\`
Search my Obsidian notes for "tri-lens"
\`\`\`

## Troubleshooting

| Issue | Fix |
|-------|-----|
| Connection refused | Make sure Obsidian is running and REST API plugin is enabled |
| 401 Unauthorized | Check API key matches in config and bat file |
| MCP not showing in tool | Restart the AI tool after config change |
| HTTPS errors | REST API uses HTTPS (port 27124), MCP proxy uses HTTP (port 3010) |

---`,

"Obsidian-API-Reader": `---

## What It Is

PowerShell and batch scripts that read Obsidian vault notes directly via the Local REST API, without needing the MCP server running. Useful for quick access and scripting.

## Scripts

| Script | What It Does |
|--------|-------------|
| \`obsidian-api-reader.ps1\` | PowerShell — list files, read notes, search vault |
| \`simple-obsidian-reader.bat\` | Batch — simple curl-based note reader |

## Usage — PowerShell

\`\`\`powershell
# List all files in vault
.\\obsidian-api-reader.ps1 -action list

# Read a specific note
.\\obsidian-api-reader.ps1 -action read -path "folder/note.md"

# Search for a term
.\\obsidian-api-reader.ps1 -action search -query "tri-lens"
\`\`\`

## Usage — Batch

\`\`\`batch
simple-obsidian-reader.bat "folder/note.md"
\`\`\`

## Direct curl Commands

\`\`\`bash
# List all files
curl -k -H "Authorization: Bearer YOUR_API_KEY" https://127.0.0.1:27124/vault/

# Read a specific note
curl -k -H "Authorization: Bearer YOUR_API_KEY" https://127.0.0.1:27124/vault/folder/note.md

# Search
curl -k -H "Authorization: Bearer YOUR_API_KEY" "https://127.0.0.1:27124/search/simple/?query=tri-lens"
\`\`\`

## Requirements

- Obsidian running with vault open
- Local REST API plugin enabled (HTTPS on port 27124)
- \`-k\` flag on curl to accept self-signed SSL cert

## Troubleshooting

| Issue | Fix |
|-------|-----|
| SSL certificate error | Use \`-k\` flag (self-signed cert) |
| 401 Unauthorized | Check API key in script matches REST API plugin |
| Connection refused | Ensure Obsidian is running with REST API enabled |
| Empty response | Verify the note path exists in the vault |

---`,

"Sync-To-Obsidian": `---

## What It Does

\`sync-to-obsidian.ps1\` dynamically scans the Tri-Lens project, classifies files using routing rules, and copies them into the Obsidian vault organized by category.

## How It Works

1. Scans the project directory recursively
2. Classifies each file based on routing rules (path patterns → vault folders)
3. Copies matched files to the appropriate Obsidian vault subfolder
4. Skips excluded folders (node_modules, .git, etc.)

## Usage

\`\`\`powershell
cd c:\\Projects\\github\\tri-lens-pipeline
.\\sync-to-obsidian.ps1
\`\`\`

## Routing Rules

Files are routed based on their path:

| Source Pattern | Vault Destination |
|---------------|-------------------|
| \`governance/**\` | \`Tri-Lens/Governance/\` |
| \`docs/**\` | \`Tri-Lens/Docs/\` |
| \`functions/**/*.js\` | \`Tri-Lens/Functions/\` |
| \`scoring-engine/**\` | \`Tri-Lens/Scoring/\` |
| \`migrations/**\` | \`Tri-Lens/Migrations/\` |
| \`*.md\` (root) | \`Tri-Lens/\` |

## Included Extensions

\`.md\`, \`.js\`, \`.py\`, \`.sql\`, \`.json\`, \`.yaml\`, \`.yml\`, \`.sh\`, \`.bat\`, \`.ps1\`, \`.txt\`

## Skipped Folders

\`node_modules\`, \`.git\`, \`.firebase\`, \`__pycache__\`, \`.venv\`, \`venv\`, \`dist\`, \`build\`, \`graphify-out\`

## Vault Location

\`\`\`
C:\\Projects\\SiiYa_Obsidian_Vault\\SiiYa_Obsidian_Vault\\Tri-Lens\\
\`\`\`

## Tri-Lens Usage

Run after major changes to keep Obsidian vault in sync:
- After new governance docs are added
- After scoring engine changes
- After migration scripts are created
- Before doing research in Obsidian

---`,

"MCP-Scripts": `---

## What These Are

Batch and PowerShell scripts that start the MCP (Model Context Protocol) server, which bridges AI tools to your Obsidian vault.

## Script Inventory

| Script | Transport | What It Does |
|--------|-----------|-------------|
| \`obsidian-mcp.bat\` | HTTP | **Primary launcher** — starts MCP server on port 3010 |
| \`start-mcp.bat\` | HTTP | Alternative launcher with extra env vars |
| \`start-mcp.ps1\` | HTTP | PowerShell version of the launcher |
| \`start-mcp-clean.bat\` | HTTP | Clean start (kills existing processes first) |
| \`start-mcp-http.bat\` | HTTP | Explicit HTTP transport |
| \`start-mcp-stdio.bat\` | stdio | For tools that launch MCP directly (Claude Desktop) |
| \`start-mcp-simple.bat\` | HTTP | Minimal config launcher |

## When to Use Which

| Scenario | Script |
|----------|--------|
| Normal daily use | \`obsidian-mcp.bat\` |
| MCP seems stuck | \`start-mcp-clean.bat\` |
| Claude Desktop (launches its own) | \`start-mcp-stdio.bat\` |
| Debugging connection issues | \`start-mcp-simple.bat\` |

## Environment Variables Set

| Variable | Value | Purpose |
|----------|-------|---------|
| \`OBSIDIAN_API_KEY\` | (from .mcp-env) | Obsidian REST API authentication |
| \`OBSIDIAN_URL\` | https://127.0.0.1:27124 | Obsidian REST API endpoint |
| \`MCP_PORT\` | 3010 | MCP server HTTP port |

## Usage

\`\`\`bash
# Start the primary MCP server
cd c:\\Projects\\github\\tri-lens-pipeline
.\\obsidian-mcp.bat

# Keep the terminal open — server runs until you close it
\`\`\`

## Testing Connectivity

After starting the server:
\`\`\`bash
# Test MCP server is running
curl http://127.0.0.1:3010/mcp

# Test Obsidian REST API directly
curl -k -H "Authorization: Bearer YOUR_KEY" https://127.0.0.1:27124/vault/
\`\`\`

## Troubleshooting

| Issue | Fix |
|-------|-----|
| Port 3010 already in use | Run \`start-mcp-clean.bat\` to kill existing process |
| Connection refused | Make sure Obsidian is running first |
| API key mismatch | Check \`.mcp-env\` matches Obsidian REST API plugin settings |
| Node not found | Ensure Node.js is installed and in PATH |

---`,

"MCP-Tool-Configs": `---

## What These Are

JSON configuration files that tell each AI tool how to connect to the Obsidian MCP server. Each tool has its own config format and install location.

## Config Files

| AI Tool | Config File | Status |
|---------|------------|--------|
| **Windsurf** | \`mcp-configs/windsurf-mcp_config.json\` | ✅ INSTALLED |
| **Claude Desktop** | \`mcp-configs/claude-desktop-config.json\` | ✅ INSTALLED |
| **ChatGPT Desktop** | \`mcp-configs/chatgpt-mcp-config.json\` | Ready (needs app) |
| **Codex CLI** | \`mcp-configs/codex-mcp-config.json\` | Ready (needs app) |
| **Gemini** | \`mcp-configs/gemini-mcp-config.json\` | Ready (needs app) |

## Install Locations

| AI Tool | Config Destination |
|---------|-------------------|
| Windsurf | \`C:\\Users\\argen\\.codeium\\windsurf\\mcp_config.json\` |
| Claude Desktop | \`C:\\Users\\argen\\AppData\\Roaming\\Claude-3p\\claude_desktop_config.json\` |
| ChatGPT | \`%LOCALAPPDATA%\\Packages\\OpenAI.ChatGPT_*\\LocalState\\mcp.json\` |
| Codex CLI | \`~/.codex/mcp.json\` |
| Gemini | Settings in Gemini app or API config |

## Two Transport Types

| Type | How It Works | Used By |
|------|-------------|---------|
| **HTTP** (serverUrl) | Connects to already-running MCP server | Windsurf |
| **stdio** | Launches MCP server directly as child process | Claude Desktop, ChatGPT, Codex, Gemini |

## Installation Steps

1. Start Obsidian and ensure REST API plugin is running
2. Copy the appropriate config file to the tool's config location
3. Restart the AI tool
4. For HTTP transport: start \`obsidian-mcp.bat\` first
5. For stdio transport: tool launches server automatically

## Verify Connection

After restarting an AI tool, try:
\`\`\`
List all files in my Obsidian vault
\`\`\`
If it returns file names from your vault, the connection works.

## Troubleshooting

| Issue | Fix |
|-------|-----|
| Tool doesn't see MCP | Restart the AI tool after copying config |
| HTTP transport fails | Make sure \`obsidian-mcp.bat\` is running |
| stdio transport fails | Check Node.js is in PATH |
| Wrong vault | Verify OBSIDIAN_URL points to correct port |

---`,

"Windsurf-Rules": `---

## What These Are

Windsurf rules are always-on instructions that govern how Windsurf (Cascade) behaves in this project. They're defined as markdown files with YAML frontmatter.

## Active Rules

### terminal_raw.md
**Trigger:** \`always_on\`
**Activation:** When prompt contains \`OUTPUT MODE: TERMINAL_RAW\`

Forces Windsurf to paste exact terminal output with zero interpretation:
- No summaries
- No bullet points
- No analysis
- No descriptions of output meaning
- No "it worked" — only raw output

**Violation = immediate hard stop on current task.**

## Rule File Format

\`\`\`markdown
---
trigger: always_on
---

### Rule Name
Rule content here...
\`\`\`

## Rule Locations

| File | What It Does |
|------|-------------|
| \`.windsurf/rules/terminal_raw.md\` | Raw terminal output mode |
| \`.windsurf/terminal_raw_rules.md\` | Backup copy of terminal raw rules |

## Windsurf Role in Tri-Lens

Per \`.windsurfrules\` and \`CLAUDE.md\`:

| Responsibility | Allowed |
|---------------|---------|
| React/UI components | ✅ |
| Frontend deploys | ✅ |
| Frontend commands | ✅ |
| Backend pipeline code | ❌ |
| DB operations | ❌ |
| \`index.js\` or scoring files | ❌ |
| Architecture decisions | ❌ |

**Current phase:** Claude Code handles all backend. Windsurf on standby for frontend only.
**Return trigger:** Pipeline stable + tests 100% green + Claude chat confirms UI build phase.

---`,

"500-AI-Projects-Reference": `---

## What It Is

A curated list of 500+ AI/ML/Deep Learning project ideas with source code, organized by domain. Useful for learning, portfolio building, and finding patterns applicable to Tri-Lens.

## Categories

| Category | Examples |
|----------|---------|
| **Machine Learning** | Regression, classification, clustering, ensemble methods |
| **Deep Learning** | CNNs, RNNs, transformers, GANs |
| **Computer Vision** | Object detection, image segmentation, OCR |
| **NLP** | Sentiment analysis, text classification, summarization, NER |
| **Reinforcement Learning** | Game playing, robotics, optimization |
| **Time Series** | Forecasting, anomaly detection, trend analysis |
| **Recommendation Systems** | Collaborative filtering, content-based |
| **Speech & Audio** | Speech recognition, audio classification |
| **Generative AI** | Text generation, image generation, style transfer |

## Tri-Lens Relevant Projects

| Project Type | Tri-Lens Application |
|-------------|---------------------|
| **Sentiment Analysis** | L1 source credibility scoring |
| **Text Classification** | Article topic classification |
| **NER (Named Entity Recognition)** | Entity extraction for corroboration |
| **Anomaly Detection** | Score drift detection |
| **Clustering** | Corroboration matrix grouping |
| **Time Series Forecasting** | Scoring trend prediction |
| **Text Summarization** | Article headline analysis for L3 |

## How to Use

1. Browse the repo by category
2. Find a project with relevant techniques
3. Study the implementation approach
4. Adapt patterns for Tri-Lens scoring engine

## Link

https://github.com/ashishpatel26/500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code`

};
